export default {
  title: 'Leaflet GeoSearch',
  typescript: true,
  themeConfig: {
    showPlaygroundEditor: true,
  },
  src: 'docs',
  dest: '.docz/dist',
  public: 'docs/assets',
  host: '0.0.0.0',
  editBranch: 'develop',
  ignore: ['CODE_OF_CONDUCT.md', 'CONTRIBUTING.md', 'LICENSE.md'],
  menu: [
    { name: 'Introduction' },
    { name: 'Usage' },
    { name: 'Leaflet Control' },
    {
      name: 'Providers',
      menu: [
        'Algolia',
        'Bing',
        'Esri',
        'Geocode Earth',
        'Google',
        'Here',
        'LocationIQ',
        'OpenCage',
        'OpenStreetMap',
        'Pelias',
        'Custom Providers',
        'Geoapify',
      ],
    },
  ],
};
